### ISSUE TITLE
[bug] video player

### ISSUE THREAD

**Issue by fallsdevil** [roozbehzarei/filester#34]
I'm having a bug where when I upload a video, when I click on the player it doesn't work and doesn't show any sign of error or anything that could identify the problem.

**Comment by roozbehzarei** [comment]
Hello Gabriel,
I'm going to need more information in order to fully understand the issue and fix it. According to your explanation, you first attempt to upload a video, then try to open it in the video player. I don't understand the relation here.
The question is, when you attempt to upload your video, does it succeed and provide you with a link to download it? Also, is your problem limited to video files only?

**Comment by fallsdevil** [comment]
I upload it, when I receive the link I paste it into the browser to test, and in the browser/website player that doesn't play the video, I tried it on the desktop too and it's the same thing.
I recorded my smartphone screen to demonstrate:

https://github.com/roozbehzarei/filester/assets/142761950/b7997448-1d43-4a1b-b552-41eb43259121

And I only uploaded video and photos, and only with videos I had problems, I don't know if I would have this same problem with audio, I didn't test it... Maybe it's a bug in the website used, I don't know.

**Comment by roozbehzarei** [comment]
Hi there,

Thank you for the thorough demonstration. As you have already guessed it, the problem is on the website's end. The duty of Filester is to upload your files on the cloud and give you the corresponding link. In your video, Filester is doing exactly that.
Your specific problem is due to transfer.sh website having a faulty video player, which is out of Filester's hands. What you can do though, is to click on the "download" button of your uploaded videos instead of playing them online.

Some workarounds you could try are:
- Update your web browser or switch to another, in this case the video player could start working properly.
- Post an issue on [transfer.sh repository](https://github.com/dutchcoders/transfer.sh) and report your problem with the same details you've provided here, they regularly update their website to fix known bugs.

**Comment by fallsdevil** [comment]
Thank you for your help!
