### ISSUE TITLE
Add Privacy Policy

### ISSUE THREAD

**Issue by DevZer0ne** [roozbehzarei/filester#35]
Can you please explain where our files are being uploaded and for how long? Is this app consuming local storage space? Stuff like background activities needs to be out there in public for better understanding of how this app actually works.

**Comment by roozbehzarei** [comment]
Hello @DevZer0ne,

There's a button in the "About" section of Filester named "[transfer.sh](https://transfer.sh/)", which is an open-source cloud storage used by Filester to upload user files. You can view its source code [here](https://github.com/dutchcoders/transfer.sh/).
Filester does not pass any user info to the cloud storage it uses, and only collects anonymous data like device model, Android version and the country of the user to help further understand users' needs and usage. It also helps fixing crashes and bugs.
"Anonymous data" as stated above, means all these collected information are not (in anyways) bound to the uploaded files or any individual.

As for the lifetime of uploaded files, transfer.sh keeps uploaded files for 14 days, which is stated in Filester after your upload succeeds.

In the end, your point is solid. These information must be accessible within the app, which is why I will transform this issue into a task to add "Privacy Policy" section to Filester in the upcoming version.
